#!/bin/zsh
#
# bootstrap installs things.

# Assume everyone's on OS X and run Homebrew (*nix-ers beware)
. script/homebrew

# Install prezto
if [[ ! -d ~/.oh-my-zsh ]] ; then
  git clone https://github.com/sorin-ionescu/prezto.git ~/.oh-my-zsh
fi

# Run the install (I'd like to pull this out of rake, eventually)
rake install
