#!/bin/sh
#
# Homebrew
#
# This installs some of the common dependencies needed (or at least desired)
# using Homebrew.

# Check for Homebrew
if test ! $(which brew)
then
  echo "  x You should probably install Homebrew first:"
  echo "    https://github.com/mxcl/homebrew/wiki/installation"
  exit
else
  echo "  + Homebrew found."
fi

# Make sure we’re using the latest Homebrew
brew update

# Upgrade any already-installed formulae
brew upgrade

# Install wget with IRI support
brew install wget --enable-iri

# Install more recent versions of some OS X tools
brew tap homebrew/dupes
brew install homebrew/dupes/vim

# Install everything else
brew install ack
brew install git
brew install tig
brew install autojump
#brew install giter8
#brew install gnupg
#brew install haskell-platform
brew install macvim
brew install vimpager
#brew install postgresql
brew install reattach-to-user-namespace
brew install tmux
brew install rlwrap
brew install scala
brew install tree
brew install xmlstarlet

# Remove outdated versions from the cellar
brew cleanup
